# External gems
gems:
  - jekyll-sitemap
  - jekyll-paginate

# Site settings
permalink: /:title
title: 荒蛮之地
subtitle: "I got a serious heartache"
email: abrasumentee@gmail.com
name: abrasumente
description: >
  深思熟虑
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "https://abrasumente233.github.io" # the base hostname & protocol for your site
cover: "assets/header_image.jpg"
logo: "assets/logo.png"
hl_style: "css/github.css"
future: true

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/page:num/"

# Disqus comments
#disqus_shortname: abcomment

# Google analytics
ga_tracking_id: "UA-66656181-1"

# Social icons and sharing options
#
# Social settings are used in two places:
# * In the footer, as links to your personal profiles
# * After each blog post for sharing widgets
#
# Example:
#
# social:
#   - name: Twitter                         # Name of the service
#     icon: twitter                         # Font Awesome icon to use (minus fa- prefix)
#     username: "@TheBenCentra"             # (User) Name to display in the footer link
#     url: https://twitter.com/TheBenCentra # URL of your profile (leave blank to not display in footer)
#     desc: Follow me on Twitter            # Description to display as link title, etc
#     share_url: http://twitter.com/share   # URL for sharing to the service (leave blank to not allow sharing)
#     share_title: ?text=                   # Title parameter for sharing URL
#     share_link: "&amp;url="               # Link parameter for sharing URL
social:
  - name: 邮件
    icon: icon-envelope
    username: abrasumentee@gmail.com
    url: mailto:abrasumentee@gmail.com
    desc: 可能会看到，可能吧

  - name: GitHub
    icon: icon-github2
    username: abrasumente233
    url: https://github.com/abrasumente233
    desc: 垃圾堆
